### PR TITLE
Calculate statistics from history

### PR DESCRIPTION
**Pull request by Dassderdie**
* Instead of calculating the statistics in the reducer and saving them in the state, they are now generated on demand in the frontend by applying the actions in order.
* To not block the main thread if this takes longer I use the `sleep` method in the frontend too -> moved it from backend to shared (this method is also very handy for simple experiments).

TODO: 
* [x] Write a migration that removes the `statistics` from the `state` @ClFeSc

### CODE REVIEW

**Comment by ClFeSc** [comment]
>     * [x]  Write a migration that removes the `statistics` from the `state` @ClFeSc

@Dassderdie Done.

**Review by ClFeSc — DISMISSED** [review]

**Comment by Dassderdie** [comment]
@ClFeSc Should this state then be version 4 or incorporated into version 3 (merge conflicts)?

**Comment by ClFeSc** [comment]
> @ClFeSc Should this state then be version 4 or incorporated into version 3 (merge conflicts)?

Version 4. Don't mix state versions, this will only break.

**Review by ClFeSc — APPROVED** [review]

**Comment by ClFeSc** [comment]
@Dassderdie I've merged `dev` into this branch. Merge when you like it.

**Pull request merged**
