### PR TITLE
Release 0.0.0

### PR DESCRIPTION
**Pull request by Dassderdie**
### Context
@christianzoellner wants a "stable" version to which he can refer interested persons. This "stable" version is the `main`-branch.

### Release process
We currently don't have a standardized release process. My proposal would be the following:
* Each release changes the version in all `package.json`-s. They should always be the same.
* This version could also be displayed in the frontend. This would make it easier to identify the current version deployed somewhere.
* I personally like versioning numbers in the format `x.y.z` where `x`, `y` and `z` are each numbers. They could be interpreted as:
   `${major}.${minor}.${patch}` - subjective, depending on the number of features introduced
* I would release this as `0.0.0` 
* I would also create a GitHub-release and link/upload the corresponding docker-image. This could later be done automatically via GitHub-actions.
* @hpi-sam/bp2022hg1 can decide how it should go from here on (and change it if they see fit).

### EDIT

The base branch will also be changed back to `main` to only show a stable `README` on the GitHub page.

### CODE REVIEW

**Comment by Dassderdie** [comment]
@ClFeSc any thoughts on this?

**Comment by ClFeSc** [comment]
> ### Context
> @christianzoellner wants a "stable" version to which he can refer interested persons. This "stable" version is the `main`-branch.

Understandable. We should never be in a position where we have to merge *699* commits at once.

> ### Release process
> We currently don't have a standardized release process. My proposal would be the following:
> 
> * Each release changes the version in all `package.json`-s. They should always be the same.

I agree. There is also `docs/swagger.yml` with a version number that should be kept in sync (by the way, at some point we could move that file to `backend`).

> * This version could also be displayed in the frontend. This would make it easier to identify the current version deployed somewhere.

I agree.

> * I personally like versioning numbers in the format `x.y.z` where `x`, `y` and `z` are each numbers. They could be interpreted as:
>   `${major}.${minor}.${patch}` - subjective, depending on the number of features introduced

Absolutely. See [semver](https://semver.org/).

> * I would release this as `0.0.0`

I would not. `0.0.0` is a bad version number in my opinion and indicates that the app basically cannot do anything. I'd rather go with `0.1.0` or even `1.0.0` at this point. See [here](https://semver.org/#faq).

> * I would also create a GitHub-release and link/upload the corresponding docker-image. This could later be done automatically via GitHub-actions.

Definitely.

> * @hpi-sam/bp2022hg1 can decide how it should go from here on (and change it if they see fit).

I agree.

> ### EDIT
> The base branch will also be changed back to `main` to only show a stable `README` on the GitHub page.

Hmm, I'm not sure about that one. This would re-introduce the problem of not-auto-closing of issues with PRs. And it could also display a slower-than-actual development activity in the project, depending on how often we'll merge into `main`. I think I'd go with keeping `dev` as the default branch but adding a note at the top of the `README.md` that `main` is the stable version and link to it.

**Comment by Dassderdie** [comment]
> > * I personally like versioning numbers in the format `x.y.z` where `x`, `y` and `z` are each numbers. They could be interpreted as:
> >   `${major}.${minor}.${patch}` - subjective, depending on the number of features introduced
> 
> Absolutely. See [semver](https://semver.org/).
> 
> > * I would release this as `0.0.0`
> 
> I would not. `0.0.0` is a bad version number in my opinion and indicates that the app basically cannot do anything. I'd rather go with `0.1.0` or even `1.0.0` at this point. See [here](https://semver.org/#faq).

I'm aware of semver, but I don't think we would use semver versioning. Semver requires a `public API`. I would argue we either don't have that or don't want to change versions based on it (because nobody is interested in it).
Nevertheless, our versioning could be very close to semver-versioning.

> > ### EDIT
> > The base branch will also be changed back to `main` to only show a stable `README` on the GitHub page.
> 
> Hmm, I'm not sure about that one. This would re-introduce the problem of not-auto-closing of issues with PRs. And it could also display a slower-than-actual development activity in the project, depending on how often we'll merge into `main`. I think I'd go with keeping `dev` as the default branch but adding a note at the top of the `README.md` that `main` is the stable version and link to it.

I created #585 for this discussion.

**Comment by ClFeSc** [comment]
> > > * I personally like versioning numbers in the format `x.y.z` where `x`, `y` and `z` are each numbers. They could be interpreted as:
> > >   `${major}.${minor}.${patch}` - subjective, depending on the number of features introduced
> > 
> > 
> > Absolutely. See [semver](https://semver.org/).
> > > * I would release this as `0.0.0`
> > 
> > 
> > I would not. `0.0.0` is a bad version number in my opinion and indicates that the app basically cannot do anything. I'd rather go with `0.1.0` or even `1.0.0` at this point. See [here](https://semver.org/#faq).
> 
> I'm aware of semver, but I don't think we would use semver versioning. Semver requires a `public API`. I would argue we either don't have that or don't want to change versions based on it (because nobody is interested in it). Nevertheless, our versioning could be very close to semver-versioning.
> ### EDIT:
> 
> https://www.jering.tech/articles/semantic-versioning-in-practice#what-software-can-semver-version

Ah, yes. I agree that semver itself is not applicable to us. I just wanted to use it as an example of the `x.y.z` version number style. So all good there.

> > > ### EDIT
> > > The base branch will also be changed back to `main` to only show a stable `README` on the GitHub page.
> > 
> > 
> > Hmm, I'm not sure about that one. This would re-introduce the problem of not-auto-closing of issues with PRs. And it could also display a slower-than-actual development activity in the project, depending on how often we'll merge into `main`. I think I'd go with keeping `dev` as the default branch but adding a note at the top of the `README.md` that `main` is the stable version and link to it.
> 
> I created #585 for this discussion.

Thanks.

---

So, apart from the `0.0.0` version number I'm happy with all the proposals here.

**Comment by Dassderdie** [comment]
> So, apart from the `0.0.0` version number I'm happy with all the proposals here.


My reasoning for `0.0.0`:
* Nobody cares about this specific release.
* I want to give the new bachelor team as much freedom as possible to decide on the versioning. It could cause confusion if we now release `1.0.0` but they decide on something different.
* All versions of our software until now had version `0.0.0` -> this here would basically just be another merge into `main`, followed by the creation of a GitHub release to provide a source for the currently newest stable version of the software.

**Comment by ClFeSc** [comment]
> > So, apart from the `0.0.0` version number I'm happy with all the proposals here.
> 
> My reasoning for `0.0.0`:
> 
>   * Nobody cares about this specific release.

Probably true 😢

>   * I want to give the new bachelor team as much freedom as possible to decide on the versioning. It could cause confusion if we now release `1.0.0` but they decide on something different.

Yes, I agree. Especially `1.0.0` would probably not be a good idea.

>   * All versions of our software until now had version `0.0.0` -> this here would basically just be another merge into `main`, followed by the creation of a GitHub release to provide a source for the currently newest stable version of the software.

Good point. With this argument, I think I'd be ok with `0.0.0` (still not a fan, though).

@Dassderdie You've requested a review from me. I hope you don't also want to have a complete code review? I think we can be quite happy with the code as we've all seen the individual changes. Should there be a functional test by @christianzoellner or @mbarkowsky like with the previous merges to `main`?

**Comment by Dassderdie** [comment]
> @Dassderdie You've requested a review from me. I hope you don't also want to have a complete code review? I think we can be quite happy with the code as we've all seen the individual changes. Should there be a functional test by @christianzoellner or @mbarkowsky like with the previous merges to `main`?

I think we can merge it now. We probably wouldn't make any functional changes in this release either way.

**Comment by ClFeSc** [comment]
> > @Dassderdie You've requested a review from me. I hope you don't also want to have a complete code review? I think we can be quite happy with the code as we've all seen the individual changes. Should there be a functional test by @christianzoellner or @mbarkowsky like with the previous merges to `main`?
> 
> I think we can merge it now. We probably wouldn't make any functional changes in this release either way.

Well, the last merge to `main` was a long time ago, so there are many functional changes. But I agree that we can merge this. I'll approve.

**Review by ClFeSc — APPROVED** [review]
For future reference, I haven't looked at any changes here, but we reviewed them when they were merged onto `dev`. So it should be good to go.

**Comment by Dassderdie** [comment]
> Well, the last merge to `main` was a long time ago, so there are many functional changes. But I agree that we can merge this. I'll approve.

Yeah, I meant we wouldn't make any further functional changes in this release as a reaction to potential functional feedback we would receive. - If that makes any sense  ^^

**Comment by ClFeSc** [comment]
> > Well, the last merge to `main` was a long time ago, so there are many functional changes. But I agree that we can merge this. I'll approve.
> 
> Yeah, I meant we wouldn't make any further functional changes in this release as a reaction to potential functional feedback we would receive. - If that makes any sense ^^

Ah, I see. Yes, that makes sense.

**Pull request merged**
