### PR TITLE
Change the patientCapacity of an RTW to 1

### PR DESCRIPTION
**Pull request by Dassderdie**

### CODE REVIEW

**Comment by Dassderdie** [comment]
@christianzoellner Is it correct that a `KTW` should be able to transport two patients?

**Comment by christianzoellner** [comment]
it depends. 

In the context of disaster assistance there are special KTWs for two patients. This would be useful for the Malteser.

In the context of regular emergency management (as practiced by the BABZ) regular KTWs have only one slot.

Is it maybe possible to have two types of KTW, e.g. `KTW` and `KTW (KatSchutz)`, with the former having 1 and the latter having 2 patients?

**Comment by Dassderdie** [comment]
@ClFeSc TODO: 
* write migration for patientCapacity

**Review by ClFeSc — COMMENTED** [review]
Changes look good, migration missing.

**Review by ClFeSc — APPROVED** [review]

**Pull request merged**
