### PR TITLE
add error pages

### PR DESCRIPTION
**Pull request by anonym-HPI**
fixes https://github.com/hpi-sam/digital-fuesim-manv/issues/244

### CODE REVIEW

**Comment by Dassderdie** [comment]
@anonym-HPI What is the current status on this?

**Comment by anonym-HPI** [comment]
As we found out we actually only need the 502 page (as all other errors should be caught by angular, except in a multi docker environment where nginx can't find the container), should we remove most of it and only have a 502 error page?

**Comment by ClFeSc** [comment]
> As we found out we actually only need the 502 page (as all other errors should be caught by angular, except in a multi docker environment where nginx can't find the container), should we remove most of it and only have a 502 error page?

Could you please elaborate on why we need a 502 error page?

**Comment by anonym-HPI** [comment]
> 

Error 502 happens in docker when nginx already started, but nodejs hasn't, in this case nginx can't proxy a request and giving a 502 error page (Bad Gateway).
Without a dedicated page, there will be just the standard nginx 502 error page. Also such a page could enable auto refresh (so the user would have not to reload again). This 502 error could also accur, when the server or crashes or is not responsive (but nginx is still running).

**Comment by anonym-HPI** [comment]
Closing this, nginx already serves the frontend and the only 502 errors would happen with /api or /socket.io
The UI can give an error notification in the top right already.

**Pull request closed without merging**
