### PR TITLE
Add note about `docker compose` to root README

### LINKED ISSUE #403: Update documentation - new docker compose (without dash)
Before the guides included using `docker-compose` and how to install it and all the commands use `docker-compose`

Docker now includes in the Desktop and Linux command line now supports a new `docker compose` command, the plugin can be installed via `sudo apt-get install docker-compose-plugin` (https://docs.docker.com/compose/install/)

The documentation should hint people at this change, so that people are not confused, when the commands are not working, as they have the Binary Standalone Version installed (`docker-compose`).

New installations of Docker will probably have `docker compose` installed by default

### PR DESCRIPTION
**Pull request by ClFeSc**
Closes #403 

Would this be enough for now?

### CODE REVIEW

**Review by anonym-HPI — COMMENTED** [review]
The question is, if we should change it to default being without the dash, for people new to docker + docker compose and make this remark, when people are using an old version and tell them how they can easily install the new one or just use it with a dash.

**Comment by Dassderdie** [comment]
> The question is, if we should change it to default being without the dash, for people new to docker + docker compose and make this remark, when people are using an old version and tell them how they can easily install the new one or just use it with a dash.

I agree with you. The new command should be the default and the old one the remark.

**Comment by Dassderdie** [comment]
> Good point, I've changed it. What should we do in `.vscode/tasks.json`? I think we have to decide on what to use there. Should we use the new version?

I'm in favor of using the newer version there too.

**Review by Dassderdie — APPROVED** [review]
Replace the `docker-compose` with `docker compose` in the `Start database` task and I am happy.

**Comment by ClFeSc** [comment]
> > Replace the `docker-compose` with `docker compose` in the `Start database` task and I am happy.
> 
> Agreed, maybe you can do smth. like with `pwd`

Like in https://github.com/hpi-sam/digital-fuesim-manv/pull/442/commits/9f5dd2918f911214fb4fe24f8e3eacf88f33a1b2?

**Review by anonym-HPI — APPROVED** [review]

**Pull request merged**
