### PR TITLE
Add Image for Johanniter Akademie NRW, Campus Münster der Johanniter-Unfall-Hilfe e.V. (JUH)

### PR DESCRIPTION
**Pull request by Greenscreen23**
Screenshot 2023-01-24 at 14-29-44 DigitalFuesimManv

Do you think this is fine @christianzoellner?

### CODE REVIEW

**Comment by Dassderdie** [comment]
You could also add the Johanniter as a project partner to the README (search for "Malteser" to see the exact paragraph).

**Comment by Greenscreen23** [comment]
> You could also add the Johanniter as a project partner to the README (search for "Malteser" to see the exact paragraph).

Good idea, I've added them there.

**Comment by christianzoellner** [comment]
looks good.

however, while you are on it, I propose that you scale down the Malteser logo a bit, it seems disproportionally large with the subtitle being larger than other logo's titles.

I can also add some spacing to the Malteser logo image file uploaded, since such sapcing is where the Johanniter Logo gets it's small size on the website from.

**Review by christianzoellner — APPROVED** [review]

**Comment by christianzoellner** [comment]
BTW @Greenscreen23 you could use this chance to add yourselves as team members on the website.

**Comment by Greenscreen23** [comment]
> BTW @Greenscreen23 you could use this chance to add yourselves as team members on the website.

Good Idea!

**Review by Nils1729 — APPROVED** [review]

**Pull request merged**
