### PR TITLE
Improve the visualisation of the PatientStatus

### PR DESCRIPTION
**Pull request by Dassderdie**
Before             |  After
:-------------------------:|:-------------------------:
image  |  image
image | image
image | image

### CODE REVIEW

**Comment by Dassderdie** [comment]
@ClFeSc Do you know why the backend test is failing? I didn't change anything in the backend...

**Comment by ClFeSc** [comment]
> @ClFeSc Do you know why the backend test is failing? I didn't change anything in the backend...

I don't see a backend test failing. The dependency check fails as there is a vulnerability in `frontend`.

**Review by ClFeSc — APPROVED** [review]

**Comment by Dassderdie** [comment]
> > @ClFeSc Do you know why the backend test is failing? I didn't change anything in the backend...
> 
> I don't see a backend test failing. The dependency check fails as there is a vulnerability in `frontend`.

I reran it and it seemed to have worked the second time. 
Here is the first attempt:
https://github.com/hpi-sam/digital-fuesim-manv/actions/runs/2714884581/attempts/1

**Comment by ClFeSc** [comment]
> > > @ClFeSc Do you know why the backend test is failing? I didn't change anything in the backend...
> > 
> > 
> > I don't see a backend test failing. The dependency check fails as there is a vulnerability in `frontend`.
> 
> I reran it and it seemed to have worked the second time. Here is the first attempt: https://github.com/hpi-sam/digital-fuesim-manv/actions/runs/2714884581/attempts/1

Ah, I see. I already saw this issue a few times in the CI. I think this happens when the CI environment is so slow that it can't run the tick often enough.

**Pull request merged**
